In [1]:
#Dependencies
import pandas as pd

In [11]:
#Import the CSVs

storms_18 = pd.read_csv("data files/Storms_2018.csv")
storms_19 = pd.read_csv("data files/Storms_2019.csv")
storms_20 = pd.read_csv("data files/Storms_2020.csv")

storms_18.head()

C:\Users\marcu\.conda\envs\PythonData\lib\site-packages\IPython\core\interactiveshell.py:3146: DtypeWarning: Columns (21,22,25) have mixed types.Specify dtype option on import or set low_memory=False.
  has_raised = await self.run_ast_nodes(code_ast.body, cell_name,

,episode_id,event_id,state,state_fips_code,event_type,cz_type,cz_fips_code,cz_name,wfo,event_begin_time,...,tor_length,tor_width,tor_other_wfo,location_index,event_range,event_azimuth,reference_location,event_latitude,event_longitude,event_point
0,121394,729396,New mexico,35,drought,Z,528,FAR NORTHEAST HIGHLANDS,ABQ,2018-01-01 00:00:00,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,121394,729392,New mexico,35,drought,Z,521,SANDIA/MANZANO MOUNTAINS,ABQ,2018-01-01 00:00:00,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,121394,729393,New mexico,35,drought,Z,519,ALBUQUERQUE METRO AREA,ABQ,2018-01-01 00:00:00,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,121394,729395,New mexico,35,drought,Z,527,RATON RIDGE/JOHNSON MESA,ABQ,2018-01-01 00:00:00,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,121394,729394,New mexico,35,drought,Z,520,LOWER RIO GRANDE VALLEY,ABQ,2018-01-01 00:00:00,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [9]:
#Merging the Data

storm_merge1 = pd.merge(storms_18, storms_19, how = "outer")
storm_merge1.head()

,episode_id,event_id,state,state_fips_code,event_type,cz_type,cz_fips_code,cz_name,wfo,event_begin_time,...,tor_length,tor_width,tor_other_wfo,location_index,event_range,event_azimuth,reference_location,event_latitude,event_longitude,event_point
0,121394,729396,New mexico,35,drought,Z,528,FAR NORTHEAST HIGHLANDS,ABQ,2018-01-01 00:00:00,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,121394,729392,New mexico,35,drought,Z,521,SANDIA/MANZANO MOUNTAINS,ABQ,2018-01-01 00:00:00,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,121394,729393,New mexico,35,drought,Z,519,ALBUQUERQUE METRO AREA,ABQ,2018-01-01 00:00:00,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,121394,729395,New mexico,35,drought,Z,527,RATON RIDGE/JOHNSON MESA,ABQ,2018-01-01 00:00:00,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,121394,729394,New mexico,35,drought,Z,520,LOWER RIO GRANDE VALLEY,ABQ,2018-01-01 00:00:00,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [15]:
storm_merge = pd.merge(storm_merge1, storms_20, how = "outer")

storm_merge.head()

C:\Users\marcu\.conda\envs\PythonData\lib\site-packages\pandas\core\reshape\merge.py:1113: UserWarning: You are merging on int and float columns where the float values are not equal to their int representation
  warnings.warn(

,episode_id,event_id,state,state_fips_code,event_type,cz_type,cz_fips_code,cz_name,wfo,event_begin_time,...,tor_length,tor_width,tor_other_wfo,location_index,event_range,event_azimuth,reference_location,event_latitude,event_longitude,event_point
0,121394,729396,New mexico,35,drought,Z,528,FAR NORTHEAST HIGHLANDS,ABQ,2018-01-01 00:00:00,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,121394,729392,New mexico,35,drought,Z,521,SANDIA/MANZANO MOUNTAINS,ABQ,2018-01-01 00:00:00,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,121394,729393,New mexico,35,drought,Z,519,ALBUQUERQUE METRO AREA,ABQ,2018-01-01 00:00:00,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,121394,729395,New mexico,35,drought,Z,527,RATON RIDGE/JOHNSON MESA,ABQ,2018-01-01 00:00:00,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,121394,729394,New mexico,35,drought,Z,520,LOWER RIO GRANDE VALLEY,ABQ,2018-01-01 00:00:00,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [13]:
storm_merge.columns

Index(['episode_id', 'event_id', 'state', 'state_fips_code', 'event_type',
       'cz_type', 'cz_fips_code', 'cz_name', 'wfo', 'event_begin_time',
       'event_timezone', 'event_end_time', 'injuries_direct',
       'injuries_indirect', 'deaths_direct', 'deaths_indirect',
       'damage_property', 'damage_crops', 'source', 'magnitude',
       'magnitude_type', 'flood_cause', 'tor_f_scale', 'tor_length',
       'tor_width', 'tor_other_wfo', 'location_index', 'event_range',
       'event_azimuth', 'reference_location', 'event_latitude',
       'event_longitude', 'event_point'],
      dtype='object')

In [ ]:
#Drop NaN columns
so